apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-lb-ds
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-vip-lb-ds
    app.kubernetes.io/version: v0.8.9
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-lb-ds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip-lb-ds
        app.kubernetes.io/version: v0.8.9
    spec:
      containers:
      - args:
        - manager
        env:
        - name: vip_arp
          value: "true"
        - name: vip_nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: vip_interface
          value: "${VIP_INTERFACE}"
        - name: vip_cidr
          value: "24"
        - name: svc_enable
          value: "true"
        - name: svc_election
          value: "true"
        - name: svc_namespace
          value: ""
        - name: address_range
          value: "${VIP_LB_RANGE}"  # <-- This is the dynamic LoadBalancer IP range
        - name: prometheus_server
          value: ":2113"
        image: ghcr.io/kube-vip/kube-vip:v0.8.9
        imagePullPolicy: IfNotPresent
        name: kube-vip
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip-lb
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-vip-lb
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kube-vip-lb-role
rules:
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["update"]
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["list", "get", "watch", "update", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list", "get", "watch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kube-vip-lb-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-vip-lb-role
subjects:
- kind: ServiceAccount
  name: kube-vip-lb
  namespace: kube-system
