apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argocd-data-zima02
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: local-pv-apps-zima02
  storageClassName: local-storage