apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${POSTGRESQL_LV_AND_PV_NAME}-pv
spec:
  capacity:
    storage: ${POSTGRESQL_LV_AND_PV_SIZE}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: ${POSTGRESQL_LV_AND_PV_SIZE}${POSTGRESQL_LV_AND_PV_SIZE}-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ${NODE}
